name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.26.0  # Updated
  firebase_analytics: ^10.8.8  # Updated
  firebase_auth: ^4.17.7  # Updated
  cloud_firestore: ^4.15.7  # Updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
