// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzONQAbRDS-leg3a9nph-M_xQPUGaF0OA',
    appId: '1:102450913225:web:0d8ba86508e9ef86371218',
    messagingSenderId: '102450913225',
    projectId: 'my-auth-b763d',
    authDomain: 'my-auth-b763d.firebaseapp.com',
    storageBucket: 'my-auth-b763d.appspot.com',
    measurementId: 'G-LR50MQ1DYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5Ah60H4VK21n5PfamcvCHUVb7oUxxsY',
    appId: '1:102450913225:android:67eabd053e58151e371218',
    messagingSenderId: '102450913225',
    projectId: 'my-auth-b763d',
    storageBucket: 'my-auth-b763d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLzd8gfE1XryqVMr4c46n_6BrW9j3QRM',
    appId: '1:102450913225:ios:bddf3a477053f721371218',
    messagingSenderId: '102450913225',
    projectId: 'my-auth-b763d',
    storageBucket: 'my-auth-b763d.appspot.com',
    iosBundleId: 'com.example.authScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLzd8gfE1XryqVMr4c46n_6BrW9j3QRM',
    appId: '1:102450913225:ios:ee0116a6ad07d93d371218',
    messagingSenderId: '102450913225',
    projectId: 'my-auth-b763d',
    storageBucket: 'my-auth-b763d.appspot.com',
    iosBundleId: 'com.example.authScreen.RunnerTests',
  );
}
